services:
  postgres:
    image: postgres:16-alpine
    container_name: devboard-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: devboard
      POSTGRES_PASSWORD: devboard
      POSTGRES_DB: devboard
    volumes:
      - devboard_pg_data:/var/lib/postgresql/data

volumes:
  devboard_pg_data:
